services:
    db:
        image: postgres:13.3
        container_name: yatb_db
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_HOST_AUTH_METHOD: trust
        volumes:
        - database_data:/var/lib/postgresql/data
        - ./init_db.sh:/docker-entrypoint-initdb.d/yatb_init_db.sh

volumes:
    database_data:
        driver: local